### ISSUE TITLE
Using a query arg or hash fragment, show a 'debug' info box for demo purposes.

### ISSUE THREAD

**Issue by gregglind** [onkeltom/pageload_braingames#3]
If #debug or such, then have a fixed, visible box explaining the test parameters.  This is for demo purposes so that moz stakeholders can see that this is a 'configured' test, and understand that it's easy to change.  This will help selling the tool internally"

**Comment by onkeltom** [comment]
I added a debug function to the test as a url parameter. Starting a test with the `?debug=true`will show a black box on top of the page. This box will show the page load progress during the animation, i.e. element id/class and defined timeout.
